/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto_final.view;


import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

import br.com.projeto_final.dto.MaterialDTO;
import br.com.projeto_final.dto.MarcineiroDTO;
import br.com.projeto_final.ctr.MaterialCTR;
import br.com.projeto_final.ctr.MarcinerioCTR;
import br.com.projeto_final.ctr.ProjetoCTR;
import br.com.projeto_final.dto.ProjetoDTO;
import java.util.Date;
/**
 *
 * @author Felipe
 */
public class Projeto2VIEW extends javax.swing.JInternalFrame {

    MarcineiroDTO marcineiroDTO = new MarcineiroDTO();
    MarcinerioCTR marcinerioCTR = new MarcinerioCTR();
    MaterialDTO materialDTO = new MaterialDTO();
    MaterialCTR materialCTR = new MaterialCTR();
    ProjetoDTO projetoDTO = new ProjetoDTO();
    ProjetoCTR projetoCTR = new ProjetoCTR();
    
    /**
     * Creates new form Projeto2VIEW
     */
    
    ResultSet rs;
    DefaultTableModel modelo_jtl_consultar_marcinerio;
    DefaultTableModel modelo_jtl_consultar_material;
    DefaultTableModel modelo_jtl_consultar_material_selecionado;
    DefaultTableModel modelo_jtl_consultar_projeto;
    
    public Projeto2VIEW() {
        initComponents();
        
        liberaCampos(false);
        liberaBotoes(true, false, false, true);
        
        modelo_jtl_consultar_marcinerio = (DefaultTableModel) jtl_consultar_marcenerio.getModel();
        modelo_jtl_consultar_material = (DefaultTableModel) jtl_consultar__material.getModel();
        modelo_jtl_consultar_material_selecionado= (DefaultTableModel) jtl_consultar_material_selecionado.getModel();
        modelo_jtl_consultar_projeto = (DefaultTableModel) jtl_consultar_projeto.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pesquisar_nome_marcenerio = new javax.swing.JTextField();
        btnPesquisarMarceneiro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_consultar_marcenerio = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pesquisa_nome_material = new javax.swing.JTextField();
        btnPesquisarMaterial = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtl_consultar__material = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtl_consultar_material_selecionado = new javax.swing.JTable();
        btnMatAdd = new javax.swing.JButton();
        btnMatRem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome_proj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        descri_proj = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtl_consultar_projeto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        pesquisa_nome_projeto = new javax.swing.JTextField();
        btnPesquisarProjeto = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcenerio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel3.setText("Nome");

        btnPesquisarMarceneiro.setText("Pesquisar");
        btnPesquisarMarceneiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarMarceneiroActionPerformed(evt);
            }
        });

        jtl_consultar_marcenerio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtl_consultar_marcenerio);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisar_nome_marcenerio, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisarMarceneiro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pesquisar_nome_marcenerio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarMarceneiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12)))); // NOI18N

        jLabel6.setText("Descrição: ");

        btnPesquisarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarMaterialActionPerformed(evt);
            }
        });

        jtl_consultar__material.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Valor"
            }
        ));
        jtl_consultar__material.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtl_consultar__materialKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jtl_consultar__material);

        jtl_consultar_material_selecionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtl_consultar_material_selecionado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtl_consultar_material_selecionadoKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jtl_consultar_material_selecionado);

        btnMatAdd.setText("+");
        btnMatAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatAddActionPerformed(evt);
            }
        });
        btnMatAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnMatAddKeyReleased(evt);
            }
        });

        btnMatRem.setText("-");
        btnMatRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatRemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisa_nome_material))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarMaterial))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnMatAdd)
                        .addGap(52, 52, 52)
                        .addComponent(btnMatRem)
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(pesquisa_nome_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMatAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMatRem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Projeto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Nome");

        jLabel2.setText("Descrição");

        descri_proj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descri_projActionPerformed(evt);
            }
        });

        jtl_consultar_projeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Marcenerio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtl_consultar_projeto);

        jLabel4.setText("Nome");

        btnPesquisarProjeto.setText("Pesquisar");
        btnPesquisarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descri_proj))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome_proj, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisa_nome_projeto))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarProjeto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome_proj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descri_proj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pesquisa_nome_projeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnExcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisarMarceneiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarMarceneiroActionPerformed
        preencheTabelaMarcenerio(pesquisar_nome_marcenerio.getText());
    }//GEN-LAST:event_btnPesquisarMarceneiroActionPerformed

    private void btnPesquisarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarMaterialActionPerformed
        preencheTabelaMaterial(pesquisa_nome_material.getText());
    }//GEN-LAST:event_btnPesquisarMaterialActionPerformed

    private void jtl_consultar__materialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtl_consultar__materialKeyReleased

    }//GEN-LAST:event_jtl_consultar__materialKeyReleased

    private void jtl_consultar_material_selecionadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtl_consultar_material_selecionadoKeyReleased
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER);
    }//GEN-LAST:event_jtl_consultar_material_selecionadoKeyReleased

    private void btnMatAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatAddActionPerformed
        adicionaMaterial(
            Integer.parseInt(String.valueOf(jtl_consultar__material.getValueAt(
                jtl_consultar__material.getSelectedRow(), 0))),
    String.valueOf(jtl_consultar__material.getValueAt(jtl_consultar__material.getSelectedRow(), 1)),
    Double.parseDouble(String.valueOf(jtl_consultar__material.getValueAt(
        jtl_consultar__material.getSelectedRow(), 2))));
    }//GEN-LAST:event_btnMatAddActionPerformed

    private void btnMatAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMatAddKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatAddKeyReleased

    private void btnMatRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatRemActionPerformed
        removeMaterialSelecionado(jtl_consultar_material_selecionado.getSelectedRow());
    }//GEN-LAST:event_btnMatRemActionPerformed

    private void descri_projActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descri_projActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descri_projActionPerformed

    private void btnPesquisarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProjetoActionPerformed
        preencheTabelaProjeto(pesquisa_nome_projeto.getText());
    }//GEN-LAST:event_btnPesquisarProjetoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        liberaCampos(true);
        liberaBotoes(false, true, true, true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(verificarPreenchimento()){
            gravar();
            limpaCampos();
            liberaBotoes(true, false, false, true);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

        public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }//Fecha método setPosicao()
    
    private void gravar(){
        projetoDTO.setNome_proj(nome_proj.getText());
        projetoDTO.setDescricao_proj(descri_proj.getText());
        marcineiroDTO.setId_mar(Integer.parseInt(String.valueOf(
            jtl_consultar_marcenerio.getValueAt(jtl_consultar_marcenerio.getSelectedRow(), 0))));
        
        JOptionPane.showMessageDialog(null, projetoCTR.inserirProjeto(projetoDTO, marcineiroDTO, jtl_consultar_material_selecionado));
    }//Fecha método gravar()
    
    
    private void preencheTabelaMaterial(String nome_material){
        try {
            modelo_jtl_consultar_material.setNumRows(0);
            materialDTO.setNome_material(nome_material);
            rs = materialCTR.consultarMaterial(materialDTO, 1);
            
            
            while(rs.next()){
                modelo_jtl_consultar_material.addRow(new Object[]{
                    rs.getString("id_material"),
                    rs.getString("nome_material"),
                    rs.getDouble("p_custo_material")
                });
            }
        }//fecha try 
        catch (Exception erTab) {
            System.out.println("Erro SQL no PreenhcerMaterial: "+ erTab);
        }
    }//fecha metado preenche tabelaMaterial
    
    
    private void adicionaMaterial(int id_material, String nome_material, double p_custo_material){
        try {
            modelo_jtl_consultar_material_selecionado.addRow(new Object[]{
                id_material,
                nome_material,
                p_custo_material
            });
        }//fecha try 
        catch (Exception erTab) {
            System.out.println("Erro SQL Adiciona Produto:" + erTab);
        }
    }
    
    
    private void removeMaterialSelecionado(int linha_selecionada){
        try {
            if(linha_selecionada >= 0){
                modelo_jtl_consultar_material_selecionado.removeRow(linha_selecionada);
                
            
            }
            
        }//fecha try 
        catch (Exception erTab) {
            System.out.println("Erro SQL Remove Produto"+ erTab);
        }
    }//fecha metado Remove
    
    
    private void liberaCampos(boolean a){
            pesquisa_nome_material.setEnabled(a);
            btnPesquisarMarceneiro.setEnabled(a);
            jtl_consultar__material.setEnabled(a);
            pesquisar_nome_marcenerio.setEnabled(a);
            btnPesquisarMaterial.setEnabled(a);
            //jtl_consultar__pro.setEnabled(a);
            btnMatAdd.setEnabled(a);
            btnMatRem.setEnabled(a);
            jtl_consultar_material_selecionado.setEnabled(a);     
    }//Fecha metodo LiberaCampos;
    
    
    private void limpaCampos(){
        pesquisa_nome_material.setText("");
        modelo_jtl_consultar_marcinerio.setNumRows(0);
        pesquisar_nome_marcenerio.setText("");
        modelo_jtl_consultar_material.setNumRows(0);
        modelo_jtl_consultar_material_selecionado.setNumRows(0);
    }//fecha metodo limpaCampos()
    
    private void liberaBotoes(boolean  a, boolean  b, boolean  c, boolean  d){
        btnNovo.setEnabled(a);
        btnSalvar.setEnabled(b);
        btnCancelar.setEnabled(c);
        btnSair.setEnabled(d);
    }
    
    private boolean verificarPreenchimento(){
        if(jtl_consultar_marcenerio.getSelectedRowCount() <= 0){
            JOptionPane.showMessageDialog(null, "Deve ser selecionado um Marceneiro");
            jtl_consultar_marcenerio.requestFocus();
            return false;
        }
        else{
            if(jtl_consultar_material_selecionado.getRowCount() <= 0){
                JOptionPane.showMessageDialog(null, "È necessario adicionar pelo menos um material no projeto");
                jtl_consultar_material_selecionado.requestFocus();
                return false;
            }
            else{
                int verifica=0;
                for (int cont = 0; cont < jtl_consultar_material_selecionado.getRowCount(); cont++) {
                    if(String.valueOf(jtl_consultar_material_selecionado.getValueAt(cont, 3)).equalsIgnoreCase("null")){
                        verifica++;
                    }
                }
                if(verifica > 0){
                    JOptionPane.showMessageDialog(null, "A quantidade de cada material utilizado deve ser informado");
                    jtl_consultar_material_selecionado.requestFocus();
                    return false;
                }
                else{
                    return true;
                }
            }
        }
    }//fecha metado verificaPreenchimento
    
    
    private void preencheTabelaMarcenerio(String nome_mar){
        try {
            modelo_jtl_consultar_marcinerio.setNumRows(0);
            
            marcineiroDTO.setNome_mar(nome_mar);
            rs = marcinerioCTR.consultarMarcinerio(marcineiroDTO, 1);
            
            while(rs.next()){
                modelo_jtl_consultar_marcinerio.addRow(new Object[]{
                    rs.getString("id_mar"),
                    rs.getString("nome_mar")
                });
            }
        }//fecha try 
        catch (Exception erTab) {
            System.out.println("Erro SQL no PreenhcerMarcenerio: "+ erTab);
        }
    }//fecha metado preenche tabelaCliente
    
    
    private void preencheTabelaProjeto(String nome_proj){
        try{
            //Limpa todas as linhas
            modelo_jtl_consultar_projeto.setNumRows(0);
            //Enquanto tiver linhas - faça
            projetoDTO.setNome_proj(nome_proj);
            rs = projetoCTR.consultarProjeto(projetoDTO, 1); //1 = é a pesquisa por nome na classe DAO
            while(rs.next()){
                modelo_jtl_consultar_projeto.addRow(new Object[]{
                  rs.getString("id_proj"),
                  rs.getString("nome_proj"),
                  rs.getString("id_mar"),
                });
            }        
        }
        catch(Exception erTab){
            System.out.println("Erro SQL PreencheProjeto: "+erTab);
        } 
        finally{
            materialCTR.CloseDB();
        }
    }//Fecha  preencheTabelaProjeto
    
    
private void preencheCamposProjeto(int id_proj) {
    try {
        projetoDTO.setId_proj(id_proj);
        rs = projetoCTR.consultarProjeto(projetoDTO, 2); // 2 = pesquisa pelo ID na classe DAO
        if (rs.next()) {
            limpaCampos();

            nome_proj.setText(rs.getString("nome_proj"));
            descri_proj.setText(rs.getString("descricao_proj"));

            // Obtendo dados do material
            //modelo_jtl_consultar_material.setNumRows(0);
            //modelo_jtl_consultar_material.addRow(new Object[]{rs.getInt("id_material"), rs.getString("nome_material"), rs.getDouble("p_custo_material")});
            //jtl_consultar__material.setRowSelectionInterval(0, 0);

            // Obtendo dados do fornecedor
            //modelo_jtl_consultar_marcinerio.setNumRows(0);
            //modelo_jtl_consultar_marcinerio.addRow(new Object[]{rs.getInt("id_mar"), rs.getString("nome_")});
            //jtl_consultar_marcenerio.setRowSelectionInterval(0, 0);

            // Definindo a quantidade
            //txt_quantidade.setText(String.valueOf(rs.getInt("quantidade")));


            //gravar_alterar = 2;
            liberaCampos(true);
        }
    } catch (Exception erTab) {
        System.out.println("Erro SQL: " + erTab);
    } finally {
        materialCTR.CloseDB();
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMatAdd;
    private javax.swing.JButton btnMatRem;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarMarceneiro;
    private javax.swing.JButton btnPesquisarMaterial;
    private javax.swing.JButton btnPesquisarProjeto;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField descri_proj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jtl_consultar__material;
    private javax.swing.JTable jtl_consultar_marcenerio;
    private javax.swing.JTable jtl_consultar_material_selecionado;
    private javax.swing.JTable jtl_consultar_projeto;
    private javax.swing.JTextField nome_proj;
    private javax.swing.JTextField pesquisa_nome_material;
    private javax.swing.JTextField pesquisa_nome_projeto;
    private javax.swing.JTextField pesquisar_nome_marcenerio;
    // End of variables declaration//GEN-END:variables
}
